### ISSUE TITLE
Can't access mega dataset

### ISSUE THREAD

**Issue by Z1zs** [billaronis/Optimal-Route-Finding-System-For-Ships-NodeJS-Dijkstra#1]
Hi thanks a lot for your great job!
I'm currently trying to utilizing the repo, but the dataset URL can't open normally. How can I prepare the MongoDB dataset?
Thanks in advance!

**Comment by billaronis** [comment]
Hello and thanks for the feedback.
It's been years since I've finished with this thesis project so I'm pretty sure it's outdated on many aspects.
I did some research on my personal files and I managed to find some data in JSON form and I believe these are the same as the files I have attached to the MEGA link (which is no longer available).  I've created a new link for the data. The folder contains weather data, ports and data of the two phases of tanker ships. -> [https://mega.nz/folder/ZQIxDLBS#4T22u27VZHA03ODsydwjIw](url)
In addition, I have added a smaller file with only Greek ports which is something I used for tests and for my essay presentation.
To help you more, I have also added a complete final weighted directed graph with many nodes and edges in the Aegean Sea that can be used as an example (data.json) so you can also skip the graph building code.
Unfortunately the URLs of the original datasets aren't available any more. As for the historical weather data, you can find more here -> [https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation](url)

I'm pretty sure, Mongo has been changed since the last time I used it. Now, it has some sort of a subscription plan with tiers. The Tier 1 is free and you can go with it. Just follow the instructions there, upload the JSON data and make sure to connect the DB properly to the server. You basically download the correct dependencies (which you can check them in your package-lock), then you set a URI to the server part so you can make connection with the db through mongoose lib(you will take it copy/paste from the Mongo enviroment, for example: 
`//const uri = "mongodb+srv://ShipsTest:1234test@usertest.s3xvs.mongodb.net/ShipsTest?retryWrites=true&w=majority";`
OR if it's local db
`const uri = "mongodb://localhost:27017/ShipsTest";`

If I find more useful data I will upload them as well to the same new MEGA link.
Enjoy!

**Comment by Z1zs** [comment]
Thank you so much for providing such detailed information about the data as well as the projects, it's very precious for me as a fresh.
I want to borrow some of the code for my course work, so I will just build a toy demo on the current project. I really appreciate all the messages you mentioned and I will try to reproduce the MongoDB through first tier.
Thanks again for the kindly and timely reply, hope you smooth in everything.
